#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
        echo "You have to be root to install SpotCurrent. Try running with sudo."
        exit 1;
fi

echo 'Installing SpotCurrent v1.0...';
chmod +x spotcurrent

cp "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/spotcurrent" /usr/bin

echo 'Installation complete. Run SpotCurrent with the command "spotcurrent".'
exit 0;
