#!/bin/bash
#Grepping out the PID of spotify
spotifyid=$(ps -ef | grep '[/]usr/share/spotify' | awk '{print $2}' | head -1)

#echo $spotifyid;

#If no PID is found, exit with the warning.
if [ -z "$spotifyid" ]; then
	echo 'Spotify not running! PID not found.';
	exit 1;
fi;

#Trapping CTRL+C
onexit()
{
	rm -f /tmp/currentsong.txt;
	if [ -e /tmp/currentartist.txt ]; then
		echo 'Deleting Artistfile!';
		rm -f /tmp/currentartist.txt;
	fi
	echo 'OK, exiting and deleting Songfile!';
	echo 'Quitting SpotCurrent...';
	exit 1;
}
trap onexit SIGINT;

echo -e 'SpotCurrent v1.0.1 by flymia\n';

#User enters the desired interval
echo -n 'Enter your preferred check-interval (Press ENTER for default 5 seconds): ';

read interval;

if [[ -n ${interval//[0-9]/} ]]; then
	echo "Contains letters! Exiting..."
	exit 1;
fi

#If nothing was read, using the default interval;
if [ -z "$interval" ]; then
	interval=5;
fi

#If another instance is running, exit.
if [ -e /tmp/currentsong.txt ]
	then
		echo 'Another instance is running! Exiting!';
		exit 1;
	else
		echo 'To abort press CTRL+C';
		echo -e 'Starting song check...\n';
		#Create the currentsong file
		touch /tmp/currentsong.txt

		#Main loop of the script
		while true; do
			#Get the current song by listing all windows and grepping the matching window with the PID
			currentsong=$(wmctrl -l -p | grep $spotifyid | sed -n 's/.*'$HOSTNAME'//p');

			if [ "$(echo $currentsong)" == 'Spotify' ]; then
				currentsong='Song paused';
			fi

			echo -n 'Current song: ';
			echo $currentsong;

			if [ $# -lt 1 ]; then
				echo -n $currentsong' ' > /tmp/currentsong.txt
			# use -t to display in two lines
			elif [ $1 == "-t" ]; then
				split=" - "
				artist=${currentsong%%${split}*}
				song=${currentsong#*${split}}
				echo $artist > /tmp/currentsong.txt
				echo $song >> /tmp/currentsong.txt
			# use -tc to display in two lines and center the artist
			elif [ $1 == "-tc" ]; then
				split=" - "
				artist=${currentsong%%${split}*}
				song=${currentsong#*${split}}
				printf "%40s\n" "$artist - " > /tmp/currentsong.txt
				printf "%40s\n" "$song" >> /tmp/currentsong.txt
                        # use -s to split the artist and song into different files
			elif [ $1 == "-s" ]; then
                             	split=" - "
				artist=${currentsong%%${split}*}
				song=${currentsong#*${split}}
				echo $artist > /tmp/currentartist.txt
				echo $song > /tmp/currentsong.txt
			fi
			# debug
			# tail /tmp/currentsong.txt
			sleep $interval;
		done
		echo 'Exiting and deleting songfile';
		rm -f /tmp/currentsong.txt
		exit 0;
fi
