#!/bin/bash
#Getting the hostname of the client
hostname=$(hostname);
#Grepping out the PID of spotify
spotifyid=$(ps -ef | grep '[/]usr/share/spotify' | awk '{print $2}' | head -1)

#echo $spotifyid;

#If no PID is found, exit with the warning.
if [ -z "$spotifyid" ]; then
	echo 'Spotify not running! PID not found.';
	exit 0;
fi;

#Trapping CTRL+C
onexit()
{
	rm -rf /tmp/currentsong.txt;
	echo 'OK, exiting and deleting Songfile!';
	exit 1;
}
trap onexit SIGINT;

echo -e 'SpotCurrent v1.0 by flymia\n';

#User enters the desired interval
echo -n 'Enter your preferred check-interval (Press ENTER for default 5 seconds): ';

read interval;

if [[ -n ${interval//[0-9]/} ]]; then
	echo "Contains letters! Exiting..."
	exit 1;
fi

#If nothing was read, using the default interval;
if [ -z "$interval" ]; then
	interval=5;
fi

#If another instance is running, exit.
if [ -e /tmp/currentsong.txt ]
	then
		echo 'Another instance is running! Exiting!';
		exit 1;
	else
		echo 'To abort press CTRL+C';		
		echo -e 'Sarting songcheck...\n';
		#Create the currentsong file
		touch /tmp/currentsong.txt
		
		#Main loop of the script
		while true; do
			#Get the current song by listing all windows and grepping the matching window with the PID
			currentsong=$(wmctrl -l -p | grep $spotifyid | sed -n 's/.*'$hostname'//p');
			
			if [ "$(echo $currentsong)" == 'Spotify' ]; then
					currentsong='Song paused';
			fi
			
			echo -n 'Current song: ';
			echo $currentsong;
			currentsong=$currentsong ;
			echo -n $currentsong' ' > /tmp/currentsong.txt
			sleep $interval;
		done
		echo 'Exiting and deleting songfile';
		rm -rf /tmp/currentsong.txt
		exit 0;
fi
