#!/usr/bin/env bash

scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then
        echo "You have to be root to uninstall SpotCurrent. Try running with sudo."
        exit 1;
fi

echo 'Uninstalling SpotCurrent v1.0.5...';

rm -f "$(which spotcurrent)"

echo 'Uninstallation complete. Goodbye and thanks for using SpotCurrent.'
exit 0;
